### PR TITLE
fixing unproperly handled lack of description

### PR DESCRIPTION
**Pull request by d4rky-pl**
Hey,

this commit should fix rest of the script which was behaving improperly due to lack of description (problems with filename generation). I was too tired yesterday to test accordingly, but this time it should be final.

### CODE REVIEW

**Comment by zeelot** [comment]
Ah, I only tested generation :) Will test and merge as soon as possible.

**Comment by d4rky-pl** [comment]
I'd be glad because there's still an issue #21 and I can't work on it without having you fixing the merge later ;)

**Comment by zeelot** [comment]
Sorry, I won't let this stay open another day. I will get to it as soon as I get off work today.

**Comment by d4rky-pl** [comment]
That would be great because I'd like to move my repository to organisation namespace and I'm not sure if issue would be updated correctly :)

I'm still not done with tasks-migrations, unless you plan some major refactorization (and as I saw you are). 

I'm planning to write my own migratins module for minion anyway because this one doesn't have migrations generator (which would be helpful and possibly later used for scaffolder I'm planning to write) and I don't think you'll even consider it because it's not why this module was written for in the first place. After what I saw FUEL's Oil is capable of, Kohana's way is somewhat against RAD principle and I'm not really satisified about it :)

**Comment by zeelot** [comment]
Thanks again, you could still share your ideas to improve on this module. If we find it useful, we could at least make it an official minion module that works alongside this one. We are pretty simplistic here though =P

**Comment by BRMatt** [comment]
> I'm planning to write my own migratins module for minion anyway because this one doesn't have migrations generator (which would be helpful and possibly later used for scaffolder I'm planning to write) and I don't think you'll even consider it because it's not why this module was written for in the first place. After what I saw FUEL's Oil is capable of, Kohana's way is somewhat against RAD principle and I'm not really satisified about it :)

I tried to go down that route (#12) but the main problem with generation is that column renames are interpreted as "DROP COLUMN, ADD COLUMN", which is obviously something you want to avoid!

Either way, if you really wanted that functionality it shouldn't be too hard to integrate with the existing module.

EDIT: Also, thanks for your contribution :)

**Comment by d4rky-pl** [comment]
> I tried to go down that route (#12) but the main problem with generation is that column renames are interpreted as "DROP COLUMN, ADD COLUMN", which is obviously something you want to avoid!

Well, not really.
MySQL:

```
ALTER TABLE t1 CHANGE a b INTEGER
```

http://dev.mysql.com/doc/refman/5.1/en/alter-table.html

PostgreSQL:

```
ALTER TABLE products RENAME COLUMN product_no TO product_number;
```

http://www.postgresql.org/docs/8.1/static/ddl-alter.html

I was planning on using [dbforge](https://github.com/ollym/dbforge/), it'd AFAIR need this feature to be coded into it though)

**Comment by BRMatt** [comment]
Ah sorry, I assumed you meant you were comparing two schemas to create a "diff".

**Comment by d4rky-pl** [comment]
No no, that _would_ be impossible, I was thinking about it before but it's too complicated and prone to errors.
I was thinking about more general approach, like Oil from FUEL. Something like:

```
./minion scaffold:generate --fields="id: {int, primary}, user_id: {int, belongsTo: 'users.id'}, content: {text}"
```

which would generate basic controller, model using templates and migration using dbforge. Or something similar, that was my first shot (if I come up with something better, I'll probably write it). 

It would save lots of time during development. Yes, I know Kohana team doesn't believe in scaffolding saying it leads to bad code but I don't share that sentiment - scaffolded controller is what it is - just a skeleton to be covered in meat. And simple one-line generation of database would save me a lot of trouble.

There could also would be something like:

```
./minion scaffold:generate --table="comments" --rename "content" --to "body"
```

or even more user friendly approach

```
./minion scaffold:migrate --action="in comments rename content to body"
```

which would work using very simple regular expressions (in \* rename \* to *) et cetera.

Too bad minion's convention of using -- for parameters is getting into way, because it could look much nicier (./minion scaffold:migrate "in comments rename content to body"), but I guess the functionality is what counts ;)

**Comment by zeelot** [comment]
For what it's worth, I use my editor to do basic 'scaffolding'. I used to use Gedit before switching to Sublime Text 2 and I had a snippet 'km{tab}' which, when used in a model, writes the class definition for you based on the path. I dislike the scaffolding features with minion because of how difficult they are to use, but maybe if they were well implemented within the editor, they could be pretty nice.

**Comment by d4rky-pl** [comment]
Hey, it's me again ;)
Writing here so both of you get the message. [I wrote my scaffolder today](https://github.com/d4rky-pl/Kohana3-Scaffy). It's still pretty sharp-edged, but it has potential for lots of things. I will work on it and add more actions ;)

I wanted to use ollym/dbforge but it was too bloated so I ported [Fuel's DBUtil](https://github.com/d4rky-pl/Kohana-DBUtil).

If you wish to use any of my code in kohana-minion or fork kohana3-scaffy into github minion's namespace - be my guest, it'd be great to keep all minion-related projects in one place anyway.

**Pull request merged**
