### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by d4rky-pl**
Yes, it's an API breakage, but considering there's no viable documentation, it shouldn't be much of a problem.

First commit changes the way script is handling --group during db:generate. It treats it now like a group instead of expecting full location. Considering that probably no one will have more than one directory for migrations in project, I've also added configuration field for default path (it's necessary if index.php is not in the same directory as APPPATH/SYSPATH) I'll leave implementing --location to you because I simply don't need it.

I also believe automatic creation of directories would be useful because it's much easier to bootstrap and create new groups now.

### CODE REVIEW

**Comment by zeelot** [comment]
All looks fine except it should not be so difficult to create migrations in places other than application. I think we can just default a --location option to application and remove the config completely. If modules are going to be using migrations, people modifying the config to stop them in places other than a 'migrations' folder would simply break everything.

**Comment by d4rky-pl** [comment]
You have a point, I didn't think about modules migrations. I'll fix the code and create new pull request.

**Comment by zeelot** [comment]
You don't have to create a new pull request, just push to this same branch and it will update automatically. As soon as everything looks good, I will merge it in :) thanks for the work. I was actually planning on doing this as soon as I finished my Kohana tickets.

**Comment by d4rky-pl** [comment]
There's just one problem that's still bugging me - if index.php is for example in public_html, running db:generate will create migrations in --location relative to index file (DOCROOT or relative path, it'll work the same). Don't you think _generate_filename should return path prepended with getcwd() ?

**Comment by zeelot** [comment]
OK, what about if --location is missing, start from where you ran the command (is that what `getcwd()` would return?) and add 'application/migrations'? Does that work?

**Comment by zeelot** [comment]
Usually, apps look like this:

```
my-app
    application
    modules
    system
    httpdocs/index.php
    minion
```

Running generate without --location should go to application/migrations, `--location=modules/auth` will still be based on where `minion` is and will create a migration in `modules/auth/migrations`

**Comment by d4rky-pl** [comment]
In most common setting - application, modules, system, index.php in one directory it doesn't even matter, because all those techniques would work the same, and in more exotic you have to put location anyway. The only difference is that --location while using DOCROOT have to be relative to index.php which is kinda counter-intuitive in contrast to getcwd(), e.g. in your case it would have to be --location='../application/migrations' (without location it would create it in httpdocs/application/migrations)

**Comment by d4rky-pl** [comment]
And with getcwd() it would be application/migrations relative to minion (i.e. my-app/application/migrations like it should be).

**Comment by zeelot** [comment]
but it seems like this is already how it works with `--group=application/migrations/my-group`, so what is changing, exactly? I guess I have to look at how it's being done now.

**Comment by zeelot** [comment]
It looks like `realpath()` works similarly to `getcwd()`

**Comment by d4rky-pl** [comment]
I've changed group behaviour in 3fc98e5 to look more like group and less like location, e.g --group=my-group --location=application/migrations, but I guess you're right and it should work like that anyway (using getcwd()). Sorry, it's 3:30 AM here, I didn't thought about checking before asking.

**Comment by zeelot** [comment]
Right, basically `$group    = rtrim(realpath($config['group']), '/').'/';` Just becomes:

```
if (empty($config['location']))
{
    $config['location'] = APPPATH;
}
$location = rtrim(realpath($config['location']), '/').'/migrations/';
```

Then when generating the filename, append the group to it. We are just splitting the group into the 2 variables to make more sense. Defaulting to `APPPATH` will make it so it works no matter where your minion file is.

**Comment by d4rky-pl** [comment]
I like that. Just one more thing, but I guess I should create another pull request for it (it's a minor thing - _generate_filename should allow numbers and dashes in filename, it's making filenames a lot more readable).

**Comment by zeelot** [comment]
Yeah, sounds good. While you're at it, could you make descriptions optional? Do you agree they should be? P.S. you can't make 2 pull requests from the same branch. You should have made a feature branch for this to make it easier to manage :) Usually, before working on changes, you would have made a branch called `feature/option-refactoring` or something along those lines. This allows your develop branch never to be different from the official one, and it allows us to see (in the git repo history) that a feature was added or worked on.

**Comment by d4rky-pl** [comment]
Sorry, I'm kinda new to working in git with more people than myself. I'll remember about it next time (and believe me, there will be, because I'm using this module in important project for me). I'm sleepy right now and prone to mistakes, is it possible for you to squash those commits into one so I won't mess your commit log? Or should I create that new branch, move code there and create a proper pull request? ;)

And one more thing: why is it called description? I'ts more a label than description. Description should be only a comment in migration (I wouldn't mind seeing it during db:migrate either, for example to inform what has been changed and why - something like commit message in git), but for a filename 'label' would work better.

**Comment by zeelot** [comment]
Well, it does get placed unaltered in the migration file as a comment at the top of the class, so it is a description. The label is basically auto generated to be the first 100 characters of the description. Don't worry about the commits being in the wrong branch this time, it's not a huge deal. Just informing you of the common way to send pull requests because it's easier to manager for both you and I.

If you want to see the description when running db:migrate, you should create an issue for that so we can discuss it. I think we added enough changes to this pull request (it starts to get really messy if we make too many changes in one pull).

**Comment by d4rky-pl** [comment]
Sure thing. Made descriptions optional, thanks for your patience and information about pull request - I still've got a lot to learn, I guess :)

**Comment by zeelot** [comment]
All good, thanks a lot for the work :) heading out now so I will test and merge the pull request some time tomorrow!

**Comment by zeelot** [comment]
Thanks for doing most of the work for me! Great improvement!

**Pull request merged**
